class QuestionAnswer {
  List<String> mathQuestionList = [
    "Which one is not\n a prime number?",
    "What is the forty percent\n of 80?",
    "Buying price:125 TK, selling\nprice for twenty five\npercent profit?",
    "Summation of two angles of a\ntriangle is 132 degree,\nthe other angle is ?",
    "Not a factor of 36 is?",
    "Estimate √97.",
    "What is the next term here\n? 7.5,15,30,60, ____",
    "Find the 9th term in this\n sequence: −4,2,8,14,…",
    "Solve for x: 30/x=10/6",
    "If a factory worker can make 5 scarves in 2 hours, how long will it take her to make 37 scarves?"
  ];

  List<String> mathAnswerList = [
    "1",
    "32",
    "156.25",
    "48 degree",
    "8",
    "between 9 & 10",
    "120",
    "44",
    "18",
    "14.8 Hrs"
  ];
  List<String> mathOptionList = [
    "2",
    "3",
    "1",
    "5",
    "42",
    "32",
    "52",
    "35",
    "154.25",
    "155.25",
    "156.25",
    "157.25",
    "42 degree",
    "48 degree",
    "38 degree",
    "58 degree",
    "36",
    "12",
    "8",
    "4",
    "between 9 & 10",
    "between 7 & 8",
    "between 10 & 11",
    "between 8 & 9",
    "130",
    "105",
    "120",
    "90",
    "44",
    "50",
    "38",
    "32",
    "18",
    "15",
    "20",
    "16",
    "15 Hrs",
    "15.8 Hrs",
    "14 Hrs",
    "14.8 Hrs"
  ];

  List<String> iqQuestionList = [
    "Find the answer that best completes the analogy:Book is to Reading as Fork is to:",
    "Which of the following can be arranged into a 5-letter English word?",
    "8:4 as 10:",
    "You are my brother but I am not your brother. Who am I?",
    "7 * 9 - 3 x 4 + 10?",
  ];
  List<String> iqAnswerList = [
    "eating",
    "T O O M T",
    "5",
    "Your sister",
    "61",
  ];
  List<String> iqOptionList = [
    "drawing",
    "writing",
    "stirring",
    "eating",
    "H R G S T",
    "T L S A Y",
    "T O O M T",
    "W Q R G S",
    "3",
    "7",
    "24",
    "5",
    "Your nephew",
    "Your Uncle",
    "Your sister",
    "Your grandfather",
    "51",
    "61",
    "71",
    "41",
  ];

  List<String> gkQuestionList = [
    "How many  Water and Sewerage Authority (WASA) in Bangladesh?",
    "How many river ports\n in Bangladesh?",
    "How many sea ports in\n Bangladesh",
    "Who is the current president\n of the USA",
    "Who is the current president\n of Bangladesh?",
    "Who is the current president\n of Pakistan?",
    "Who is the current president\n of India?",
    "What is the first privately funded company to reach orbit around Earth?",
    "Full form of EAC?",
    "When did the fifth BIMSTEC \nconference held",
    "Which is the most sound\n polluted city?",
    "Who is the richest person\n in the earth?",
    "Total population of the earth?",
    "Highest populated country\n in the world?",
    "Which country has the highest\n population increasing rate?",
    "Which country has the lowest\npopulation increasing rate?",
    "Bangladesh's total \npopulation is :",
    "Population increasing rate\n in Bangladesh is:",
    "Most expensive city in\n the world is:",
    "Most cheapest city in\n the world is:",
    "World's first paperless\n city is:",
    "Longest day is:",
    "Longest night is:",
    "Smallest country is",
    "Biggest country is",
    "Richest country in the\n world is:",
    "Poorest country in the\n world is:",
    "Longest river in the\n world",
    "Largest ocean in the\n world",
    "Biggest forest in the\n world",
  ];
  List<String> gkAnswerList = [
    "5",
    "37",
    "3",
    "Joe Biden",
    "Abdul Hamid",
    "Shahbaz Sharif",
    "Ram Nath Kovind",
    "SpaceX",
    "East African Community",
    "30th March, 2022",
    "Dhaka",
    "Elon Mask",
    "795.40 crore",
    "China",
    "Syria",
    "Lebanon",
    "16.79 crore",
    "0.9 %",
    "Tel Aviv",
    "Damascus",
    "Dubai",
    "21th June",
    "22th December",
    "Vatican City",
    "Russia",
    "Monaco",
    "Burundi",
    "Nile",
    "Pacific Ocean",
    "Amazon rainforest"
  ];
  List<String> gkOptionList = [
    "2",
    "6",
    "8",
    "5",
    "30",
    "35",
    "37",
    "40",
    "3",
    "4",
    "1",
    "7",
    "Hilari Clinton",
    "Tony Blare",
    "Barak Obama",
    "Joe Biden",
    "Sheikh Hasina",
    "Abdul Hamid",
    "Shirin Sharmin Chawdhury",
    "Mosharrof Hossain",
    "Shahbaz Sharif",
    "Asif Ali Zardari",
    "Imran Khan",
    "Parvez Mosharrof",
    "Narendra Modi",
    "Ram Nath Kovind",
    "APJ Abul Kalam",
    "Momota Banarjee",
    "Nasa",
    "Roskosmos",
    "UK Space Agency",
    "SpaceX",
    "East Asian Confederation",
    "East Asian Community",
    "East African Confederation",
    "East African Community",
    "30th March, 2022",
    "29th March, 2022",
    "28th March, 2022",
    "31th March, 2022",
    "Dhaka",
    "New Delhi",
    "Mumbai",
    "Islamabad",
    "Bil Gates",
    "Waren Buffet",
    "Jack Ma",
    "Elon Mask",
    "780.40 crore",
    "785.40 crore",
    "790.40 crore",
    "795.40 crore",
    "India",
    "Canada",
    "Russia",
    "China",
    "Ghana",
    "Nigeria",
    "Syria",
    "Saudi Arabia",
    "Japan",
    "Lebanon",
    "Switzerland",
    "Germany",
    "15.79 crore",
    "16.79 crore",
    "17.79 crore",
    "16.89 crore",
    "1.2 %",
    "0.8 %",
    "1.5 %",
    "0.9 %",
    "Tokyo",
    "London",
    "Paris",
    "Tel Aviv",
    "Kathmandu",
    "Gujarat",
    "Damascus",
    "Havana",
    "Moscow",
    "Singapore city",
    "Abu dhabi",
    "Dubai",
    "21th June",
    "22th June",
    "21th April",
    "22th April",
    "22th January",
    "22th February",
    "21th December",
    "22th December",
    "Nauru",
    "Tuvalu",
    "Vatican City",
    "San Marino",
    "Egypt",
    "Russia",
    "Brazil",
    "china",
    "Monaco",
    "Liechtenstein",
    "Luxembourg",
    "Singapore",
    "Central African Republic",
    "Congo",
    "Malawi",
    "Burundi",
    "Amazon",
    "Nile",
    "Mississippi",
    "Yellow River",
    "Atlantic Ocean",
    "Pacific Ocean",
    "Antarctic Ocean",
    "Indian Ocean",

    "Congo Rainforest",
    "Daintree Forest",
    "Amazon Rainforest",
    "Sundarban",
  ];

  List<String> stQuestionList = [
    "What is a Galaxy?",
    "Pedology is related to:",
    "Fist satellite of Bangladesh is:",
    "Fuel used in rocket",
    "SPARSO belongs to:",
    "Why do things fall down?",
    "First high level programming language is:",
    "WWW stands for:",
    "Symbol of Gold is:",
    "pH indicates:",
    "pH of blood is:",
    "Chemical formula of stomach acid is:",
    "DNA stands for:",
    "CPU of human body is:",
    "WIFI stands for:"
  ];

  List<String> stAnswerList = [
    "Huge collection of gas, dust,\nand billions of stars\nand their solar systems.",
    "Soil",
    "Bangabandhu Satellite-1",
    "2 & 4",
    "Bangladesh",
    "for gravitational force",
    "FORTARN",
    "World wide web",
    "Au",
    "Both",
    "8",
    "HCl",
    "Deoxyribonucleic Acid",
    "Brain",
    "Wireless fidelity"
  ];

  List<String> stOptionList = [
    "Huge collection of gas, dust, \nand billions of stars\n and their solar systems.",
    "Huge collection of moon",
    "Huge collection of sun",
    "Huge collection of planet",
    "Soil",
    "Sky",
    "Ocean",
    "Chemical",
    "Satellite-1",
    "Bangabandhu Satellite-1",
    "Sheikh Mujib Satellite-1",
    "Sheikh Hasina Satellite-1",
    "Kerosene",
    "Petrol",
    "Liquid Hydrogen",
    "2 & 4",
    "Bangladesh",
    "Switzerland",
    "Singapore",
    "India",
    "for magnetic force",
    "for gravitational force",
    "for neuclear force",
    "for tension force",
    "Ada",
    "Pascal",
    "FORTARN",
    "C",
    "World wide wave",
    "Wide web world",
    "Wave world wide",
    "World wide web",
    "G",
    "Ag",
    "Au",
    "Go",
    "Acidity",
    "Basicity",
    "Both",
    "None",
    "6",
    "7",
    "8",
    "9",
    "H2SO4",
    "HCL",
    "HNO3",
    "C6H8O7",
    "Dirybo nucleic Acid",
    "Doubly nucleic Acid",
    "Deoxyribonucleic Acid",
    "Deoxy neuclieic Acid",
    "Heart",
    "Head",
    "Brain",
    "Forehead",
    "Wireless fieldality",
    "Wireless fitelity",
    "Wireless fidelity",
    "none"

  ];
}
